[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps =
  bodmer/TFT_eSPI

upload_protocol = esptool

monitor_speed = 115200

build_flags =
  -Os
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DUSER_SETUP_LOADED=1

  ; Un/comment the below to add/remove refuse bin tracker
  ; -DADD_BINS=1
  
  ; Define the TFT driver, pins etc. here:
  -DST7735_DRIVER=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=15
  -DTFT_DC=12
  -DTFT_RST=4
  -DTFT_BL=25
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_FONT6=1
  -DLOAD_FONT7=1
  -DLOAD_FONT8=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1
  -DSPI_FREQUENCY=40000000
  -DTHIS_BLACK=0x0
  -DTHIS_YELLOW=0xF800
  -DTHIS_RED=0xFFE0
  -DBL_MIN=0
  -DBL_MAX=255
